### ISSUE TITLE
pytest needed as extra dependency when using ro-crate-validator-py

### ISSUE THREAD

**Issue by kinow** [ResearchObject/ro-crate-validator-py#4]
From the WIP PR: https://github.com/ResearchObject/runcrate/pull/17/files#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52R45

![image](https://user-images.githubusercontent.com/304786/227347571-e1f2893d-0ffa-4e40-b0be-f192520e03fe.png)

Probably because of a loose `import` in this module (there could be others): https://github.com/ResearchObject/ro-crate-validator-py/blob/main/src/rocrateValidator/semanticCheck.py#L11

**Comment by stain** [comment]
Thanks, @kinow! 

@Logan-174 Are you able to give me access to https://pypi.org/project/rocrateValidator/ so I can make another release?  username `stain`
